#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'g12-prii3-move-turtlebot','console_scripts','draw_number'
__requires__ = 'g12-prii3-move-turtlebot'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('g12-prii3-move-turtlebot', 'console_scripts', 'draw_number')()
    )
